### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by gcormier** [chunkysteveo/OpenEPaperLink-HA-Weatherman#13]
Did not succeed much in getting this going. I'm taking a step back to just start from scratch and looking at things - have fixed a few on the way, but here's what I think the next hurdle is.

I am calling this service manually in HA using Developer tools
```
service: weather.get_forecasts
target:
  entity_id: weather.home
data:
  type: hourly
response_variable: weather_home_hourly
```
This is the answer : `Failed to call service weather.get_forecasts. Weather entity 'weather.home' does not support 'hourly' forecast`

I am seeing this in my startup logs, but I don't think this matters much until the above could be resolved?
![image](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/assets/8388983/4cfcd758-c664-46f2-a3f7-bf1ddb0acc94)

Note that `type: daily` works fine.
