### ISSUE TITLE
Hourly weather entity removed in HA 2024.3

### ISSUE THREAD

**Issue by CrazyCoder** [chunkysteveo/OpenEPaperLink-HA-Weatherman#18]
See https://github.com/home-assistant/core/pull/97023 and the breaking changes list in the release notes: https://www.home-assistant.io/blog/2024/03/06/release-20243/#backward-incompatible-changes.

Will it affect the configs here?

```
    action:
      - service: weather.get_forecasts
        target:
          entity_id: weather.home
        data:
          type: hourly
        response_variable: weather_home_hourly
```
