### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by CrazyCoder** [chunkysteveo/OpenEPaperLink-HA-Weatherman#22]
Stopped working after HA 2024.4 update.

```
Error: Error rendering data template: TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
```
service: open_epaper_link.drawcustom
data:
  dry-run: false
  background: white
  rotate: 0
  payload:
    - type: icon
      value: '{{ state_attr(''sensor.weatherman_data_tag'',''moon_phase'') | string }}'
      x: 85
      'y': 1
      size: 18
      color: black
    - type: text
      value: >-
        {{ state_attr('sensor.weatherman_data_tag','wm_temp_0') | string }}{{
        state_attr('sensor.weatherman_data_tag','temperature_unit') }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 125
      'y': 47
      size: 18
      color: >-
        {{'black' if state_attr('sensor.weatherman_data_tag','wm_temp_0') >
        severe_temp_low else 'red' }}
      anchor: mt
    - type: icon
      value: >-
        weather-{{ state_attr('sensor.weatherman_data_tag','wm_cond_0') | string
        }}
      x: 108
      'y': 13
      size: 34
      color: >-
        {{'red' if state_attr('sensor.weatherman_data_tag','wm_cond_0') in
        severe_weather else 'black' }}
    - type: text
      value: >-
        {{ state_attr('sensor.weatherman_data_tag','wm_temp_1') | string }}{{
        state_attr('sensor.weatherman_data_tag','temperature_unit') }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 174
      'y': 47
      size: 18
      color: >-
        {{'black' if state_attr('sensor.weatherman_data_tag','wm_temp_1') >
        severe_temp_low else 'red' }}
      anchor: mt
    - type: icon
      value: >-
        weather-{{ state_attr('sensor.weatherman_data_tag','wm_cond_1') | string
        }}
      x: 157
      'y': 13
      size: 34
      color: >-
        {{'red' if state_attr('sensor.weatherman_data_tag','wm_cond_1') in
        severe_weather else 'black' }}
    - type: text
      value: >-
        {{ state_attr('sensor.weatherman_data_tag','wm_temp_2') | string }}{{
        state_attr('sensor.weatherman_data_tag','temperature_unit') }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 223
      'y': 47
      size: 18
      color: >-
        {{'black' if state_attr('sensor.weatherman_data_tag','wm_temp_2') >
        severe_temp_low else 'red' }}
      anchor: mt
    - type: icon
      value: >-
        weather-{{ state_attr('sensor.weatherman_data_tag','wm_cond_2') | string
        }}
      x: 206
      'y': 13
      size: 34
      color: >-
        {{'red' if state_attr('sensor.weatherman_data_tag','wm_cond_2') in
        severe_weather else 'black' }}
    - type: text
      value: >-
        {{ state_attr('sensor.weatherman_data_tag','wm_temp_3') | string }}{{
        state_attr('sensor.weatherman_data_tag','temperature_unit') }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 272
      'y': 47
      size: 18
      color: >-
        {{'black' if state_attr('sensor.weatherman_data_tag','wm_temp_3') >
        severe_temp_low else 'red' }}
      anchor: mt
    - type: icon
      value: >-
        weather-{{ state_attr('sensor.weatherman_data_tag','wm_cond_3') | string
        }}
      x: 255
      'y': 13
      size: 34
      color: >-
        {{'red' if state_attr('sensor.weatherman_data_tag','wm_cond_3') in
        severe_weather else 'black' }}
    - type: text
      value: '{{ state_attr(''sensor.weatherman_data_tag'',''wm_temp_4'') | string }}'
      font: ../../media/GothamRnd-Bold.ttf
      x: 122
      'y': 111
      size: 14
      color: >-
        {{'black' if state_attr('sensor.weatherman_data_tag','wm_temp_4') >
        severe_temp_low else 'red' }}
      anchor: rt
    - type: text
      value: /
      font: ../../media/GothamRnd-Bold.ttf
      x: 125
      'y': 112
      size: 14
      color: black
      anchor: mt
    - type: text
      value: '{{ state_attr(''sensor.weatherman_data_tag'',''wm_temp_4_low'') | string }}'
      font: ../../media/GothamRnd-Bold.ttf
      x: 128
      'y': 118
      size: 14
      color: >-
        {{'black' if state_attr('sensor.weatherman_data_tag','wm_temp_4_low') >
        severe_temp_low else 'red' }}
      anchor: lt
    - type: icon
      value: >-
        weather-{{ state_attr('sensor.weatherman_data_tag','wm_cond_4') | string
        }}
      x: 108
      'y': 78
      size: 34
      color: >-
        {{'red' if state_attr('sensor.weatherman_data_tag','wm_cond_4') in
        severe_weather else 'black' }}
    - type: text
      value: '{{ state_attr(''sensor.weatherman_data_tag'',''wm_temp_5'') | string }}'
      font: ../../media/GothamRnd-Bold.ttf
      x: 171
      'y': 111
      size: 14
      color: >-
        {{'black' if state_attr('sensor.weatherman_data_tag','wm_temp_5') >
        severe_temp_low else 'red' }}
      anchor: rt
    - type: text
      value: /
      font: ../../media/GothamRnd-Bold.ttf
      x: 174
      'y': 112
      size: 14
      color: black
      anchor: mt
    - type: text
      value: '{{ state_attr(''sensor.weatherman_data_tag'',''wm_temp_5_low'') | string }}'
      font: ../../media/GothamRnd-Bold.ttf
      x: 177
      'y': 118
      size: 14
      color: >-
        {{'black' if state_attr('sensor.weatherman_data_tag','wm_temp_5_low') >
        severe_temp_low else 'red' }}
      anchor: lt
    - type: icon
      value: >-
        weather-{{ state_attr('sensor.weatherman_data_tag','wm_cond_5') | string
        }}
      x: 157
      'y': 78
      size: 34
      color: >-
        {{'red' if state_attr('sensor.weatherman_data_tag','wm_cond_5') in
        severe_weather else 'black' }}
    - type: text
      value: '{{ state_attr(''sensor.weatherman_data_tag'',''wm_temp_6'') | string }}'
      font: ../../media/GothamRnd-Bold.ttf
      x: 220
      'y': 111
      size: 14
      color: >-
        {{'black' if state_attr('sensor.weatherman_data_tag','wm_temp_6') >
        severe_temp_low else 'red' }}
      anchor: rt
    - type: text
      value: /
      font: ../../media/GothamRnd-Bold.ttf
      x: 223
      'y': 112
      size: 14
      color: black
      anchor: mt
    - type: text
      value: '{{ state_attr(''sensor.weatherman_data_tag'',''wm_temp_6_low'') | string }}'
      font: ../../media/GothamRnd-Bold.ttf
      x: 226
      'y': 118
      size: 14
      color: >-
        {{'black' if state_attr('sensor.weatherman_data_tag','wm_temp_6_low') >
        severe_temp_low else 'red' }}
      anchor: lt
    - type: icon
      value: >-
        weather-{{ state_attr('sensor.weatherman_data_tag','wm_cond_6') | string
        }}
      x: 206
      'y': 78
      size: 34
      color: >-
        {{'red' if state_attr('sensor.weatherman_data_tag','wm_cond_6') in
        severe_weather else 'black' }}
    - type: text
      value: '{{ state_attr(''sensor.weatherman_data_tag'',''wm_temp_7'') | string }}'
      font: ../../media/GothamRnd-Bold.ttf
      x: 269
      'y': 111
      size: 14
      color: >-
        {{'black' if state_attr('sensor.weatherman_data_tag','wm_temp_7') >
        severe_temp_low else 'red' }}
      anchor: rt
    - type: text
      value: /
      font: ../../media/GothamRnd-Bold.ttf
      x: 272
      'y': 112
      size: 14
      color: black
      anchor: mt
    - type: text
      value: '{{ state_attr(''sensor.weatherman_data_tag'',''wm_temp_7_low'') | string }}'
      font: ../../media/GothamRnd-Bold.ttf
      x: 275
      'y': 118
      size: 14
      color: >-
        {{'black' if state_attr('sensor.weatherman_data_tag','wm_temp_7_low') >
        severe_temp_low else 'red' }}
      anchor: lt
    - type: icon
      value: >-
        weather-{{ state_attr('sensor.weatherman_data_tag','wm_cond_7') | string
        }}
      x: 255
      'y': 78
      size: 34
      color: >-
        {{'red' if state_attr('sensor.weatherman_data_tag','wm_cond_7') in
        severe_weather else 'black' }}
    - type: text
      value: >-
        {{ '%0.2d' | format(state_attr('sensor.weatherman_data_tag','wm_time_0')
        | int) | string | upper }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 125
      'y': 2
      size: 12
      color: black
      anchor: mt
    - type: text
      value: >-
        {{ '%0.2d' | format(state_attr('sensor.weatherman_data_tag','wm_time_1')
        | int) | string | upper }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 174
      'y': 2
      size: 12
      color: black
      anchor: mt
    - type: text
      value: >-
        {{ '%0.2d' | format(state_attr('sensor.weatherman_data_tag','wm_time_2')
        | int) | string | upper }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 223
      'y': 2
      size: 12
      color: black
      anchor: mt
    - type: text
      value: >-
        {{ '%0.2d' | format(state_attr('sensor.weatherman_data_tag','wm_time_3')
        | int) | string | upper }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 272
      'y': 2
      size: 12
      color: black
      anchor: mt
    - type: text
      value: >-
        {{ state_attr('sensor.weatherman_data_tag','wm_time_4') | string | upper
        }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 125
      'y': 67
      size: 12
      color: black
      anchor: mt
    - type: text
      value: >-
        {{ state_attr('sensor.weatherman_data_tag','wm_time_5') | string | upper
        }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 174
      'y': 67
      size: 12
      color: black
      anchor: mt
    - type: text
      value: >-
        {{ state_attr('sensor.weatherman_data_tag','wm_time_6') | string | upper
        }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 223
      'y': 67
      size: 12
      color: black
      anchor: mt
    - type: text
      value: >-
        {{ state_attr('sensor.weatherman_data_tag','wm_time_7') | string | upper
        }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 272
      'y': 67
      size: 12
      color: black
      anchor: mt
    - type: line
      fill: black
      width: 1
      x_start: 125
      y_start: 64
      x_end: 272
      y_end: 64
    - type: text
      value: >-
        {{ states('sensor.average_outside_temperature') | round | int(0) }}{{
        state_attr('sensor.weatherman_data_tag','temperature_unit') }}
      font: ../../media/GothamRnd-Bold.ttf
      x: 52
      'y': 94
      size: 38
      anchor: mt
      color: >-
        {{'black' if states('sensor.average_outside_temperature') | round >
        severe_temp_low else 'red' }}
    - type: icon
      value: >-
        weather-{{ state_attr('sensor.weatherman_data_tag','wm_cond_now') |
        string }}
      x: 6
      'y': 2
      size: 92
      color: >-
        {{'red' if state_attr('sensor.weatherman_data_tag','wm_cond_now') in
        severe_weather else 'black' }}
target:
  entity_id:
    - open_epaper_link.0000021EE4583B13
```

Also noticed this error in the logs:

```
Template variable error: 'None' has no attribute 'split' when rendering '{% set cond_moon = state_attr('sensor.moon_phase', 'icon') %} {{ cond_moon.split('mdi:')[1] }}'
```
