### ISSUE TITLE
weatherman_data_tag not populating

### ISSUE THREAD

**Issue by nigels0** [chunkysteveo/OpenEPaperLink-HA-Weatherman#29]
I'm having a weird issue here - in that the data_tag is partially populating.

moon_phase: moon-waxing-gibbous
sun_next_rising: 5:06 AM
sun_next_setting: 8:53 PM
temperature_unit: null
wind_speed_unit: null
precipitation_unit: null
pressure_unit: null
wm_cond_now: null
wm_temp_now: null
wm_wind_speed_now: null
wm_wind_dir_now: null
wm_dew_point_now: null
wm_humidity_now: null
wm_cloud_coverage_now: null
wm_pressure_now: null
wm_cond_0: null
..
..

I've checked that the forecast entity is indeed weather.home 

{%- for state in states | selectattr('domain','equalto','weather')   %}
         {{  state.entity_id }}
         {%- endfor -%}

returns: weather.home
 
- and the units are showing in the developer tools :
temperature: 16.9
dew_point: 14.1
temperature_unit: °C
humidity: 83
cloud_coverage: 10.2
pressure: 1012.9
pressure_unit: hPa
wind_bearing: 41.4
wind_speed: 5.4
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
attribution: >-
  Weather forecast from met.no, delivered by the Norwegian Meteorological
  Institute.
friendly_name: Forecast Home
supported_features: 3

I've tried this on a different instance of HA and it works fine.
in developer tools, in the Template section, 

"{{ state_attr('weather.home','pressure_unit') }}"

returns "hPa" as it should.

**Comment by nigels0** [comment]
Well I've identified that it isn't recognising weather.home in the sensor, so I've hard-coded weather.home instead of the variable set in the trigger.

now the problem is getting data out of weather.get_forecasts - it just isn't working for the automation - with null values for wm_cond_0 onward in the weatherman_data_tag.

running the service :Get Forecasts with weather.home as the entity and hourly or daily as the type in developer tools gives me correct information

**Comment by chunkysteveo** [comment]
Perhaps it might be a format for the quotes for the entity weather. This is the start of my sensor, which works perfectly:

```
  - trigger:
      platform: time_pattern
      minutes: "/15"
      variables:
        forecast_entity: 'weather.home'
#         {%- for state in states | selectattr('domain','equalto','weather')   %}
#         {{  state.entity_id }}
#         {%- endfor -%}
    action:
      - service: weather.get_forecasts
        target:
          entity_id: "{{forecast_entity}}"
        data:
          type: hourly
        response_variable: weather_home_hourly
      - service: weather.get_forecasts
        target:
          entity_id: "{{forecast_entity}}"
        data:
          type: daily
        response_variable: weather_home_daily
```
