### ISSUE TITLE
"Template rendered invalid entity IDs" when multiple weather providers are present

### ISSUE THREAD

**Issue by CrazyCoder** [chunkysteveo/OpenEPaperLink-HA-Weatherman#35]
I finally updated from the hardcoded `weather.home` to the new template:

```
      variables:
        forecast_entity: >
         {%- for state in states | selectattr('domain','equalto','weather')   %}
         {{  state.entity_id }}
         {%- endfor -%}
```

On my system, with two ecobee thermostats, this code returns three entities, and I get the following error in the logs:

```
Logger: homeassistant.helpers.script.trigger_update_coordinator
Source: helpers/script.py:2026
First occurred: 08:15:00 (7 occurrences)
Last logged: 09:45:00

Trigger Update Coordinator: Error executing script. Error for call_service at pos 1: Template rendered invalid entity IDs: weather.first_floor weather.second_floor weather.home
```

**Comment by CrazyCoder** [comment]
Yes, that's what I did when I got this error. Would be nice to get it fixed or documented, though.

```
  - trigger:
      platform: time_pattern
      minutes: "/15"
      variables:
        forecast_entity: >
          {{ 'weather.home' }}
```
