### ISSUE TITLE
[suggestion] Sensor: last trigger as status instead of "OK"

### ISSUE THREAD

**Issue by krissen** [chunkysteveo/OpenEPaperLink-HA-Weatherman#7]
Hi,

Thanks for the templates! Works well.

I've made two changes. One, I think is genuinely useful; the other is more aesthetic, and might or might not be your liking.

1) In the template, I've changed so that instead of status "OK", status of the sensor is timestamp of last triggered.

```yaml
  - name: Weatherman Data Tag
    state: "{{ now().isoformat() }}"
```

Status could then for example be: `2023-11-14T20:15:00.249120+01:00`.

2) I changed the color of temperature to a template evaluating to red if subzero. For example,
```yaml
color: >-
  {%if state_attr('sensor.weatherman_data_tag', 'wm_temp_7') | int < 0 %}red
  {%else %}black
  {%endif%}
```
It might then looks as below.
![open_epaper_link 0000026c3a143b1d](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/assets/2943684/5716237e-dbec-4ec3-af60-6089f12691a8)

In the example code above, it only considered the average temperature of the day, not lowest. Might add the condition that if _either_ avg or low temp is subzero, colour would be red; haven't decided yet.

Anyway, just mentioning the above in case someone else would find it useful.

**Comment by svenove** [comment]
I’ve made a 4.2" version (see PR) and there I colored just the numbers that were below 0. So if lowest was under 0 and highest was over 0, just the low number would be red.

It requires a bit more code, since each low/high will require 3 text blocks…

Just an additional idea to consider. :) 

Example:
(quite cold now, so just one black number, but you get the idea :p)
![IMG_4771](https://github.com/chunkysteveo/OpenEPaperLink-HA-Weatherman/assets/4579212/c50a2074-3740-45ca-b5f5-e6d692c0ca0c)

**Comment by krissen** [comment]
@svenove And wind as well. Nice!

**Comment by chunkysteveo** [comment]
The status of timestamp is awesome... the OK was just thrown in there to have a state! I'll add that in for sure!

And yeah - check out @krissen PR for the 4.2".... he's already implemented red sub zero temps, and various 'bad weather' events. I'm going to pull that in and update the 2.9" tag to reflect that too 👍🏻

**Comment by krissen** [comment]
Thank you @svenove for addressing my laziness. ;-)

Here's how I implemented it for the 2.9", in case it might save you some work @chunkysteveo.

I've tested it for different temps (single/double digits etc.), and thought it looked alright. Looking at the numbers, it should be offset somewhat compared to the original, but in effect I found this to look centred. Maybe my eye is off, don't know. (Used middle-anchoring to have the same y for all three pieces and, like @svenove, left-middle-right anchoring which should mean locations are fixed regardless of digits in the temperature.)

```yaml
          - type: text
            value: >-
              {{ state_attr('sensor.weatherman_data_tag','wm_temp_4') | string }}
            font: ../../media/GothamRnd-Bold.ttf
            x: 118
            "y": 119
            size: 14
            color: >-
              {%if state_attr('sensor.weatherman_data_tag', 'wm_temp_4') | int < 0 %}red
              {%else %}black
              {%endif%}
            anchor: rm
          - type: text
            value: " / "
            font: ../../media/GothamRnd-Bold.ttf
            x: 122
            "y": 119
            size: 14
            color: black
            anchor: mm
          - type: text
            value: >-
              {{ state_attr('sensor.weatherman_data_tag','wm_temp_4_low') | string }}
            font: ../../media/GothamRnd-Bold.ttf
            x: 125
            "y": 119
            size: 14
            color: >-
              {%if state_attr('sensor.weatherman_data_tag', 'wm_temp_4_low') | int < 0 %}red
              {%else %}black
              {%endif%}
            anchor: lm
          - type: icon
            value: >-
              weather-{{ state_attr('sensor.weatherman_data_tag','wm_cond_4') |
              string }}
            x: 108
            "y": 78
            size: 34
            color: black
          - type: text
            value: >-
              {{ state_attr('sensor.weatherman_data_tag','wm_temp_5') | string }}
            font: ../../media/GothamRnd-Bold.ttf
            x: 167
            "y": 119
            size: 14
            color: >-
              {%if state_attr('sensor.weatherman_data_tag', 'wm_temp_5') | int < 0 %}red
              {%else %}black
              {%endif%}
            anchor: rm
          - type: text
            value: " / "
            font: ../../media/GothamRnd-Bold.ttf
            x: 171
            "y": 119
            size: 14
            color: black
            anchor: mm
          - type: text
            value: >-
              {{ state_attr('sensor.weatherman_data_tag','wm_temp_5_low') | string }}
            font: ../../media/GothamRnd-Bold.ttf
            x: 174
            "y": 119
            size: 14
            color: >-
              {%if state_attr('sensor.weatherman_data_tag', 'wm_temp_5_low') | int < 0 %}red
              {%else %}black
              {%endif%}
            anchor: lm
          - type: icon
            value: >-
              weather-{{ state_attr('sensor.weatherman_data_tag','wm_cond_5') |
              string }}
            x: 157
            "y": 78
            size: 34
            color: black
          - type: text
            value: >-
              {{ state_attr('sensor.weatherman_data_tag','wm_temp_6') | string }}
            font: ../../media/GothamRnd-Bold.ttf
            x: 216
            "y": 119
            size: 14
            color: >-
              {%if state_attr('sensor.weatherman_data_tag', 'wm_temp_6') | int < 0 %}red
              {%else %}black
              {%endif%}
            anchor: rm
          - type: text
            value: " / "
            font: ../../media/GothamRnd-Bold.ttf
            x: 220
            "y": 119
            size: 14
            color: black
            anchor: mm
          - type: text
            value: >-
              {{ state_attr('sensor.weatherman_data_tag','wm_temp_6_low') | string }}
            font: ../../media/GothamRnd-Bold.ttf
            x: 223
            "y": 119
            size: 14
            color: >-
              {%if state_attr('sensor.weatherman_data_tag', 'wm_temp_6_low') | int < 0 %}red
              {%else %}black
              {%endif%}
            anchor: lm
          - type: icon
            value: >-
              weather-{{ state_attr('sensor.weatherman_data_tag','wm_cond_6') |
              string }}
            x: 206
            "y": 78
            size: 34
            color: black
          - type: text
            value: >-
              {{ state_attr('sensor.weatherman_data_tag','wm_temp_7') | string }}
            font: ../../media/GothamRnd-Bold.ttf
            x: 265
            "y": 119
            size: 14
            color: >-
              {%if state_attr('sensor.weatherman_data_tag', 'wm_temp_7') | int < 0 %}red
              {%else %}black
              {%endif%}
            anchor: rm
          - type: text
            value: " / "
            font: ../../media/GothamRnd-Bold.ttf
            x: 269
            "y": 119
            size: 14
            color: black
            anchor: mm
          - type: text
            value: >-
              {{ state_attr('sensor.weatherman_data_tag','wm_temp_7_low') | string }}          
            font: ../../media/GothamRnd-Bold.ttf
            x: 272
            "y": 119
            size: 14
            color: >-
              {%if state_attr('sensor.weatherman_data_tag', 'wm_temp_7_low') | int < 0 %}red
              {%else %}black
              {%endif%}
            anchor: lm
```
