### ISSUE TITLE
[suggestion] Change current condition temp to round instead of int

### ISSUE THREAD

**Issue by krissen** [chunkysteveo/OpenEPaperLink-HA-Weatherman#8]
Hi,

Yet another very minor suggestion. In the automation, the current condition -temperature isn't rounded but concatenated into an integer. I.e., a temperature of -3.6 would show as "-3".

```yaml
- type: text
          value: |-
            {{ state_attr('weather.home','temperature') | int(0) }}{{
             state_attr('weather.home','temperature_unit') }}
```

Suggestion, change from `int(0)` to `round`. Thus, a temperature of -3.6 would show as "-4"
