### ISSUE TITLE
Low/high forecast today only show from now till midnight

### ISSUE THREAD

**Issue by svenove** [chunkysteveo/OpenEPaperLink-HA-Weatherman#9]
The low/high doesn’t show the lowest/highest temperature forecasted today, but show from “now” till midnight. So looking a the forecast at 8pm shows only lowest/highest for the next 4 hours. And since the tag already show the next hours individually it would be better to show todays forecasted low/high for the entire day. 

This would mean updating the low/high forecast for today either only at midnight or that each update it check to see if the forecast is a new low or new high. 

Any suggestion on how to implement that the easiest way?

**Comment by chunkysteveo** [comment]
Is this for your 4.2" display, as I don't show the low/high for the current day, just the current temperature and the temperature forecasted for the upcoming hours?

**Comment by svenove** [comment]
On your 2.9" photo, isn’t the “18/13” under Monday the forecasted high/low for today?

**Comment by chunkysteveo** [comment]
Ahh I see what you mean. no - the first day in the 4-day forecase on the tag is/was using the forecast from the main "weather.home" sensor from met.no, so the temperature and templow are different values compared to the current temperature, see example below taken from the met.no sensor right now... you can see temperature is different to forecast[0]temperature:

```
temperature: 9.4
dew_point: 6.9
temperature_unit: °C
humidity: 85
cloud_coverage: 82.8
pressure: 1011.9
pressure_unit: hPa
wind_bearing: 271.9
wind_speed: 21.93
wind_speed_unit: mph
visibility_unit: mi
precipitation_unit: mm
forecast:
  - condition: cloudy
    datetime: "2023-11-15T12:00:00+00:00"
    wind_bearing: 274.8
    temperature: 9.9
    templow: 6.1
    wind_speed: 21.93
    precipitation: 0.3
    humidity: 81
    ```
    
I suppose what we should really do for the daily forecast is shift the array by +1, so we're forecasting for the following day, not the same day?!
